### ISSUE TITLE
The connection to the server was reset while the page was loading

### ISSUE THREAD

**Issue by maaixprt** [mjhea0/passport-local-express4#10]
Hi,

When I try to access the url in the page it is giving error all the time: 
The connection was reset

The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by mjhea0** [comment]
Which URL? Which page?

**Comment by maaixprt** [comment]
I am using docker container. When I try to access url: 127.0.0.1:3000 It is redirecting again and again. Page is index page.

**Comment by mjhea0** [comment]
This isn't the place for troubleshooting. Use StackOverflow for that. Try looking at the Docker logs to see if there's an error.
